language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

before_script:
  - npm install

after_failure:
  - cat /home/travis/build/metavurt/ng-bla/npm-debug.log

branches:
  only: master

cache:
  directories: node_modules

script:
  - npm run build.prod.exp

  addons:
    code_climate:
        repo_token: 83598ae1a16ff81da8cd506999202972ebbf9e88fd6a3cabcb0584403f802e91